l_korean:
 dmm_mod_333: "$shroud_rising_settings.1.name$"
 edict_shroud_rising_settings: "(모드 메뉴) §H$shroud_rising_settings.1.name$§!"
 edict_shroud_rising_settings_desc: "§R슈라우드 라이징§!에 대한 현재 설정을 엽니다."
 shroud_rising_settings.1.a: "$FE_DIFFICULTY$ $SETTINGS$"
 shroud_rising_settings.1.a.tooltip: "$DIFFICULTY_ADJUSTED_AI_MODIFIERS$.\n모드의 난이도 설정을 설정합니다."
 shroud_rising_settings.1.b.tooltip: "메뉴 닫기."
 shroud_rising_settings.1.c: "$OUTLINER_FALLEN_EMPIRES$ §G$ON$§!의 경우"
 shroud_rising_settings.1.c.tooltip: "$shroud_rising_2_poi$는 $OUTLINER_FALLEN_EMPIRES$에 대해 생성합니다"
 shroud_rising_settings.1.d: "$OUTLINER_FALLEN_EMPIRES$ §R$OFF$§!의 경우"
 shroud_rising_settings.1.d.tooltip: "$shroud_rising_2_poi$ $OUTLINER_FALLEN_EMPIRES$에 대해 생성하지 않습니다."
 shroud_rising_settings.1.desc: "아래에서 옵션을 선택하여 §M슈라우드 라이징§! 환경을 설정하세요. 난이도 설정이 §L$DIFFICULTY_CAPTAIN$§! 이상이라면 §P2x§! 이상으로 플레이하는 것이 좋습니다.\n\n이 설정은 플레이 도중 언제든 시행령 메뉴를 통해 열 수 있습니다."
 shroud_rising_settings.1.name: "§M슈라우드 라이징 $SETTINGS$§!"
 shroud_rising_settings.12.a.tooltip: "$pc_eye_of_terror$ 위기 상황이 발생할 확률은 100%입니다."
 shroud_rising_settings.12.b.tooltip: "매년 $pc_eye_of_terror$ 위기 상황이 발생할 확률은 75%입니다."
 shroud_rising_settings.12.c.tooltip: "매년 $pc_eye_of_terror$ 위기 상황이 발생할 확률은 50%입니다."
 shroud_rising_settings.12.d.tooltip: "매년 $pc_eye_of_terror$ 위기 상황이 발생할 확률은 25%입니다."
 shroud_rising_settings.12.desc: "§ME공포의 눈§! 위기 상황이 발생할 가능성을 선택하세요. 선택 사항은 요구 사항을 충족한 후 위기가 발생할 전체 연간 확률을 나타냅니다.\n\n§R게임이 시작된 후에는 변경할 수 없습니다.§!\n\n스폰되려면 게임 중반이어야 하며 위기에는 로봇이 아닌/게슈탈트가 아닌 몰락 제국이나 사이오닉 주요 종족이 있는 AI 제국이 하나 이상 필요합니다."
 shroud_rising_settings.12.e: "5%"
 shroud_rising_settings.12.e.tooltip: "매년 $pc_eye_of_terror$ 위기 상황이 발생할 확률은 5%입니다."
 shroud_rising_settings.12.f: "§L뒤로§!"
 shroud_rising_settings.12.f.tooltip: "위기는 자연스럽게 생성되지 않지만, 원하시면 항상 수동으로 발동할 수 있습니다.\n\n더 자세한 지침은 모드 페이지를 확인하세요."
 shroud_rising_settings.2.0.desc: "현재 선택 항목: $shroud_rising_settings.default$"
 shroud_rising_settings.2.1.desc: "현재 선택 항목: $shroud_rising_settings.2.g$"
 shroud_rising_settings.2.10.desc: "현재 선택 항목: $shroud_rising_settings.2.b$\n\n'§T포스가 함께하길.§!'"
 shroud_rising_settings.2.2.desc: "현재 선택 항목: $shroud_rising_settings.2.f$"
 shroud_rising_settings.2.25.desc: "현재 선택 항목: $shroud_rising_settings.2.a$\n\n'§T오늘 어떤 약을 복용하셨나요?§!'"
 shroud_rising_settings.2.3.desc: "현재 선택 항목: $shroud_rising_settings.2.e$"
 shroud_rising_settings.2.4.desc: "현재 선택 항목: $shroud_rising_settings.2.d$"
 shroud_rising_settings.2.5.desc: "현재 선택 항목: $shroud_rising_settings.2.c$"
 shroud_rising_settings.2.a: "§P25x§!"
 shroud_rising_settings.2.b: "§P10x§!"
 shroud_rising_settings.2.c: "§P5x§!"
 shroud_rising_settings.2.d: "§P4x§!"
 shroud_rising_settings.2.desc: "Select the overall strength £military_power£ of the §MShroud Rising§! crisis, this will affect enemy spawns that emerge from Rifts, §MThe Eye of Terror§! and other related events.\n\nThis setting can be changed at any time throughout your play-through and is independent of the vanilla crisis difficulty strength.\n\n"
 shroud_rising_settings.2.e: "§P3x§!"
 shroud_rising_settings.2.f: "§P2x§!"
 shroud_rising_settings.2.g: "§P1.5x§!"
 shroud_rising_settings.2.h: "메인 메뉴로 돌아가기"
 shroud_rising_settings.default: "§L$DEFAULT_GENDER$§!"
 sr_difficulty_1: "$paragon.5265.c$ x1.5"
 sr_difficulty_10: "$paragon.5265.c$ x10"
 sr_difficulty_2: "$paragon.5265.c$ x2"
 sr_difficulty_25: "$paragon.5265.c$ x25"
 sr_difficulty_3: "$paragon.5265.c$ x3"
 sr_difficulty_4: "$paragon.5265.c$ x4"
 sr_difficulty_5: "$paragon.5265.c$ x5"
