l_japanese:
 dmm_mod_333: "$shroud_rising_settings.12.name$"
 edict_shroud_rising_settings: "§M[MOD MENU]§! §YShroud Rising§!"
 edict_shroud_rising_settings_desc: "Shroud Risingの現在の設定を開きます。"
 shroud_rising_settings.1.a: "難易度設定"
 shroud_rising_settings.1.a.tooltip: "MODの難易度設定を調整します。"
 shroud_rising_settings.1.b.tooltip: "メニューを閉じる。"
 shroud_rising_settings.1.c: "$ON$ $OUTLINER_FALLEN_EMPIRES$"
 shroud_rising_settings.1.c.tooltip: "$shroud_rising_2_poi$ spawns for $OUTLINER_FALLEN_EMPIRES$"
 shroud_rising_settings.1.d: "§R$OFF$ $OUTLINER_FALLEN_EMPIRES$§!"
 shroud_rising_settings.1.d.tooltip: "$shroud_rising_2_poi$ spawns §RNOT§! for $OUTLINER_FALLEN_EMPIRES$"
 shroud_rising_settings.1.desc: "以下のオプションを選択すると、 Shroud Risingの体験が調整されます。\n難易度設定が§Y$DIFFICULTY_CAPTAIN$§!以上の場合は、 §P2x§!以上でのプレイを推奨します。\n\nこの設定は、 プレイ中どのタイミングでも、 $EDICT$から開けます。"
 shroud_rising_settings.1.name: "§MShroud Rising $SETTINGS$§!"
 shroud_rising_settings.12.a.tooltip: "100％の確率で「$jp_sr_crisis_name_eye$」の危機連鎖が発動します。"
 shroud_rising_settings.12.b.tooltip: "毎年75％の確率で「$jp_sr_crisis_name_eye$」の危機連鎖が発動します。"
 shroud_rising_settings.12.c.tooltip: "毎年50％の確率で「$jp_sr_crisis_name_eye$」の危機連鎖が発動します。"
 shroud_rising_settings.12.d.tooltip: "毎年25％の確率で「$jp_sr_crisis_name_eye$」の危機連鎖が発動します。"
 shroud_rising_settings.12.desc: "§M$jp_sr_crisis_name_eye$§!の危機連鎖が発生する可能性を選択してください。\n選択肢は、 条件を満たしたときに危機が発生する確率を年単位で表しています。\n\n§Rゲーム開始後に変更はできません。§!\n\n危機を発生させるには、 ゲーム中盤以降であり、 非ロボット・非ゲシュタルトの$COUNTRY_FALLEN_EMPIRE$、 または超能力者がメイン種族のAI帝国が最低一ヶ国必要です。"
 shroud_rising_settings.12.e: "5%"
 shroud_rising_settings.12.e.tooltip: "毎年5％の確率で「$jp_sr_crisis_name_eye$」の危機連鎖が発動します。"
 shroud_rising_settings.12.f: "§L無効§!"
 shroud_rising_settings.12.f.tooltip: "危機は自然に発生しなくなりますが、 必要であればいつでも手動で発動できます。\n\nより具体的な方法は、 MODのページでご確認ください。"
 shroud_rising_settings.2.0.desc: "Current selection: $shroud_rising_settings.default$"
 shroud_rising_settings.2.1.desc: "$jp_shroud_rising_settings_intro$§Lデフォルト§!"
 shroud_rising_settings.2.10.desc: "$jp_shroud_rising_settings_intro$§P10x§!\n\n§T『フォースが共にあらんことを。』§!"
 shroud_rising_settings.2.2.desc: "$jp_shroud_rising_settings_intro$§P2x§!"
 shroud_rising_settings.2.25.desc: "$jp_shroud_rising_settings_intro$§P25x§!\n\n§T『今日はどんな薬をキメてる？』§!"
 shroud_rising_settings.2.3.desc: "$jp_shroud_rising_settings_intro$§P3x§!"
 shroud_rising_settings.2.4.desc: "$jp_shroud_rising_settings_intro$§P4x§!"
 shroud_rising_settings.2.5.desc: "$jp_shroud_rising_settings_intro$§P5x§!"
 shroud_rising_settings.2.a: "§P25x§!"
 shroud_rising_settings.2.b: "§P10x§!"
 shroud_rising_settings.2.c: "§P5x§!"
 shroud_rising_settings.2.d: "§P4x§!"
 shroud_rising_settings.2.desc: "Select the overall strength £military_power£ of the §MShroud Rising§! crisis, this will affect enemy spawns that emerge from Rifts, §MThe Eye of Terror§! and other related events.\n\nThis setting can be changed at any time throughout your playthrough and is independent of the vanilla crisis difficulty strength.\n\n"
 shroud_rising_settings.2.e: "§P3x§!"
 shroud_rising_settings.2.f: "§P2x§!"
 shroud_rising_settings.2.g: "§Lデフォルト§!"
 shroud_rising_settings.2.h: "メインメニューへ戻る"
 shroud_rising_settings.default: "§L$DEFAULT_GENDER$§!"
 sr_difficulty_1: "$paragon.5265.c$ x1.5"
 sr_difficulty_10: "強化 x10"
 sr_difficulty_2: "強化 x2"
 sr_difficulty_25: "強化 x25"
 sr_difficulty_3: "強化 x3"
 sr_difficulty_4: "強化 x4"
 sr_difficulty_5: "強化 x5"
